version: '3.8'

services:
  postgres-test:
    image: postgres:16-alpine
    container_name: stashy-db-test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stashy_test
    ports:
      - '5433:5432'
    volumes:
      - postgres_data_test:/var/lib/postgresql/data
    networks:
      - stashy-network-test
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U postgres -d stashy_test' ]
      interval: 2s
      timeout: 5s
      retries: 10

  redis-test:
    image: redis:7-alpine
    container_name: stashy-redis-test
    command: redis-server --requirepass 'testpassword'
    ports:
      - '6380:6379'
    volumes:
      - redis_data_test:/data
    networks:
      - stashy-network-test
    healthcheck:
      test: [ 'CMD', 'redis-cli', '-a', 'testpassword', 'ping' ]
      interval: 2s
      timeout: 5s
      retries: 10

  # MinIO (S3 Compatible Storage)
  minio:
    image: minio/minio:latest
    container_name: stashy-minio-test
    command: server /data --console-address ":9001"
    ports:
      - "9003:9000"
      - "9004:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    volumes:
      - minio_data_test:/data
    networks:
      - stashy-network-test
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

  # Create MinIO Buckets
  createbuckets:
    image: minio/mc
    container_name: stashy-createbuckets-test
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c " /usr/bin/mc config host add myminio http://minio:9000 ${MINIO_ROOT_USER:-minioadmin} ${MINIO_ROOT_PASSWORD:-minioadmin}; /usr/bin/mc mb myminio/${AWS_S3_BUCKET_NAME:-stashy-bucket}; /usr/bin/mc anonymous set public myminio/${AWS_S3_BUCKET_NAME:-stashy-bucket}; exit 0; "
    networks:
      - stashy-network-test

networks:
  stashy-network-test:
    driver: bridge
volumes:
  postgres_data_test:
  redis_data_test:
  minio_data_test:


