/**
 * Standardized error codes for the application.
 * These codes are used for:
 * 1. Backend: Thrown with BusinessException
 * 2. Frontend: Mapped to localized error messages
 *
 * Naming convention: {DOMAIN}_{ACTION}_{REASON}
 * Examples: AUTH_LOGIN_FAILED, WORD_NOT_FOUND, VALIDATION_REQUIRED_FIELD
 */

// - AUTH_*: 인증 관련 (UNAUTHORIZED, TOKEN_EXPIRED, LOGIN_FAILED 등)
// - USER_*: 사용자 관련 (NOT_FOUND, NICKNAME_TAKEN 등)
// - WORD_*: 단어 관련
// - DEFINITION_*: 정의 관련
// - VALIDATION_*: 입력값 검증 관련
// - NETWORK_*: 네트워크 오류 (프론트엔드 전용)

// ============================================
// Authentication Errors (AUTH_*)
// ============================================
export const ERROR_CODES = {
  // Authentication
  AUTH_UNAUTHORIZED: "AUTH_UNAUTHORIZED",
  AUTH_TOKEN_EXPIRED: "AUTH_TOKEN_EXPIRED",
  AUTH_TOKEN_INVALID: "AUTH_TOKEN_INVALID",
  AUTH_LOGIN_FAILED: "AUTH_LOGIN_FAILED",
  AUTH_SESSION_EXPIRED: "AUTH_SESSION_EXPIRED",

  // Authorization
  FORBIDDEN_ACCESS: "FORBIDDEN_ACCESS",
  FORBIDDEN_RESOURCE: "FORBIDDEN_RESOURCE",

  // User
  USER_NOT_FOUND: "USER_NOT_FOUND",
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  USER_NICKNAME_TAKEN: "USER_NICKNAME_TAKEN",
  USER_NICKNAME_INVALID: "USER_NICKNAME_INVALID",

  // Word
  WORD_NOT_FOUND: "WORD_NOT_FOUND",
  WORD_ALREADY_EXISTS: "WORD_ALREADY_EXISTS",
  WORD_CREATE_FAILED: "WORD_CREATE_FAILED",
  WORD_UPDATE_FAILED: "WORD_UPDATE_FAILED",
  WORD_DELETE_FAILED: "WORD_DELETE_FAILED",

  // Definition
  DEFINITION_NOT_FOUND: "DEFINITION_NOT_FOUND",
  DEFINITION_CREATE_FAILED: "DEFINITION_CREATE_FAILED",
  DEFINITION_UPDATE_FAILED: "DEFINITION_UPDATE_FAILED",
  DEFINITION_DELETE_FAILED: "DEFINITION_DELETE_FAILED",

  // Like
  LIKE_ALREADY_EXISTS: "LIKE_ALREADY_EXISTS",
  LIKE_NOT_FOUND: "LIKE_NOT_FOUND",

  // Follow
  FOLLOW_ALREADY_EXISTS: "FOLLOW_ALREADY_EXISTS",
  FOLLOW_NOT_FOUND: "FOLLOW_NOT_FOUND",
  FOLLOW_SELF_NOT_ALLOWED: "FOLLOW_SELF_NOT_ALLOWED",

  // Report
  REPORT_ALREADY_EXISTS: "REPORT_ALREADY_EXISTS",
  REPORT_NOT_FOUND: "REPORT_NOT_FOUND",
  REPORT_SELF_NOT_ALLOWED: "REPORT_SELF_NOT_ALLOWED",

  // Validation
  VALIDATION_FAILED: "VALIDATION_FAILED",
  VALIDATION_REQUIRED_FIELD: "VALIDATION_REQUIRED_FIELD",
  VALIDATION_INVALID_FORMAT: "VALIDATION_INVALID_FORMAT",
  VALIDATION_TOO_LONG: "VALIDATION_TOO_LONG",
  VALIDATION_TOO_SHORT: "VALIDATION_TOO_SHORT",

  // File Upload
  FILE_UPLOAD_FAILED: "FILE_UPLOAD_FAILED",
  FILE_TOO_LARGE: "FILE_TOO_LARGE",
  FILE_INVALID_TYPE: "FILE_INVALID_TYPE",

  // Server
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",

  // Network (frontend only)
  NETWORK_ERROR: "NETWORK_ERROR",
  NETWORK_TIMEOUT: "NETWORK_TIMEOUT",

  // Generic
  UNKNOWN_ERROR: "UNKNOWN_ERROR",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

/**
 * API Error Response format returned by backend
 */
export type ApiErrorResponse = {
  statusCode: number;
  errorCode: ErrorCode;
  message: string;
  timestamp: string;
  path: string;
  details?: Record<string, unknown>;
};
