/**
 * This file was automatically generated by scripts/generate-db-types.js.
 * DO NOT EDIT MANUALLY.
 */

import {
  admin_users, 
  badges, 
  definition_histories, 
  definitions, 
  event_aggregates, 
  events, 
  follows, 
  likes, 
  migration_history, 
  notifications, 
  refresh_tokens, 
  reports, 
  terms, 
  user_badge_progress, 
  user_badges, 
  user_login_streaks, 
  users, 
  vw_definitions_with_likes, 
  vw_latest_definitions, 
  vw_words_with_stats, 
  words, 
} from "@stashy/shared";

declare module "knex/types/tables" {
  export interface Tables {
    admin_users: admin_users,
    badges: badges,
    definition_histories: definition_histories,
    definitions: definitions,
    event_aggregates: event_aggregates,
    events: events,
    follows: follows,
    likes: likes,
    migration_history: migration_history,
    notifications: notifications,
    refresh_tokens: refresh_tokens,
    reports: reports,
    terms: terms,
    user_badge_progress: user_badge_progress,
    user_badges: user_badges,
    user_login_streaks: user_login_streaks,
    users: users,
    vw_definitions_with_likes: vw_definitions_with_likes,
    vw_latest_definitions: vw_latest_definitions,
    vw_words_with_stats: vw_words_with_stats,
    words: words,
  }
}
  