/**
 * This file was automatically generated by scripts/generate-db-types.js.
 * DO NOT EDIT MANUALLY.
 */

export type AdminRole = "super_admin" | "developer" | "operator";

export type admin_users = {
  id: string;
  username: string;
  password: string;
  role: AdminRole;
  must_change_password?: boolean | null;
  last_login?: Date | null;
  created_at?: Date | null;
  updated_at?: Date | null;
  deleted_at?: Date | null;
};

export type badges = {
  id: string;
  code: string;
  name: string;
  description?: string | null;
  icon?: string | null;
  category: string;
  event_type: string;
  threshold: number;
  is_active: boolean;
  created_at: Date;
  updated_at: Date;
  deleted_at?: Date | null;
};

export type definition_histories = {
  id: string;
  definition_id: string;
  content: string;
  tags?: any | null;
  media_urls?: any | null;
  created_at: Date;
};

export type definitions = {
  id: string;
  content: string;
  word_id: string;
  user_id: string;
  term_id: string;
  created_at: Date;
  updated_at: Date;
  deleted_at?: Date | null;
  tags?: any | null;
  media_urls?: any | null;
  is_public: boolean;
};

export type event_aggregates = {
  id: string;
  type: string;
  user_id?: string | null;
  aggregate_key: string;
  count: number;
  first_occurrence: Date;
  last_occurrence: Date;
  metadata?: any | null;
  period_start: Date;
  period_end: Date;
  created_at: Date;
  updated_at: Date;
  deleted_at?: Date | null;
};

export type events = {
  id: string;
  type: string;
  user_id?: string | null;
  payload: any;
  metadata?: any | null;
  created_at: Date;
  updated_at: Date;
  deleted_at?: Date | null;
};

export type follows = {
  id: string;
  follower_id: string;
  following_id: string;
  created_at: Date;
  updated_at: Date;
  deleted_at?: Date | null;
};

export type likes = {
  id: string;
  user_id: string;
  definition_id: string;
  created_at: Date;
  updated_at: Date;
  deleted_at?: Date | null;
};

export type migration_history = {
  sequence_id: number;
  filename: string;
  executed_at?: Date | null;
};

export type notifications = {
  id: string;
  user_id: string;
  type: string;
  title: string;
  message?: string | null;
  actor_id?: string | null;
  target_url?: string | null;
  is_read: boolean;
  created_at: Date;
  updated_at: Date;
  deleted_at?: Date | null;
};

export type refresh_tokens = {
  id: string;
  user_id: string;
  token: string;
  expires_at: Date;
  created_at: Date;
  updated_at: Date;
  deleted_at?: Date | null;
  from_admin: boolean;
};

export type reports = {
  id: string;
  reporter_id: string;
  reported_user_id: string;
  definition_id?: string | null;
  reason: string;
  status: string;
  description?: string | null;
  created_at: Date;
  updated_at: Date;
  resolved_at?: Date | null;
};

export type terms = {
  id: string;
  text: string;
  number: number;
  created_at: Date;
  updated_at: Date;
  deleted_at?: Date | null;
};

export type user_badge_progress = {
  id: string;
  user_id: string;
  event_type: string;
  count: number;
  last_updated: Date;
  created_at: Date;
  updated_at: Date;
  deleted_at?: Date | null;
};

export type user_badges = {
  id: string;
  user_id: string;
  badge_id: string;
  earned_at: Date;
  updated_at: Date;
  deleted_at?: Date | null;
};

export type user_login_streaks = {
  id: string;
  user_id: string;
  current_streak: number;
  longest_streak: number;
  last_login_at: Date;
  created_at?: Date | null;
  updated_at?: Date | null;
};

export type users = {
  id: string;
  google_id?: string | null;
  email: string;
  nickname: string;
  profile_picture?: string | null;
  created_at: Date;
  updated_at: Date;
  deleted_at?: Date | null;
  bio?: string | null;
  suspended_at?: Date | null;
};

export type vw_definitions_with_likes = {
  id: string;
  content?: string | null;
  word_id?: string | null;
  user_id?: string | null;
  term_id?: string | null;
  created_at?: Date | null;
  updated_at?: Date | null;
  deleted_at?: Date | null;
  tags?: any | null;
  media_urls?: any | null;
  is_public?: boolean | null;
  likes_count?: string | null;
};

export type vw_latest_definitions = {
  id: string;
  content?: string | null;
  word_id?: string | null;
  user_id?: string | null;
  term_id?: string | null;
  created_at?: Date | null;
  updated_at?: Date | null;
  deleted_at?: Date | null;
  tags?: any | null;
  media_urls?: any | null;
  is_public?: boolean | null;
  user_nickname?: string | null;
  user_profile_picture?: string | null;
  likes_count?: string | null;
};

export type vw_words_with_stats = {
  id: string;
  term?: string | null;
  user_id?: string | null;
  created_at?: Date | null;
  updated_at?: Date | null;
  deleted_at?: Date | null;
  definition_count?: string | null;
  public_definition_count?: string | null;
  contributor_count?: string | null;
};

export type words = {
  id: string;
  term: string;
  user_id: string;
  created_at: Date;
  updated_at: Date;
  deleted_at?: Date | null;
};

export type DBTableNameStr =
  | "admin_users"
  | "badges"
  | "definition_histories"
  | "definitions"
  | "event_aggregates"
  | "events"
  | "follows"
  | "likes"
  | "migration_history"
  | "notifications"
  | "refresh_tokens"
  | "reports"
  | "terms"
  | "user_badge_progress"
  | "user_badges"
  | "user_login_streaks"
  | "users"
  | "vw_definitions_with_likes"
  | "vw_latest_definitions"
  | "vw_words_with_stats"
  | "words";
export interface DBTableMap {
  admin_users: admin_users;
  badges: badges;
  definition_histories: definition_histories;
  definitions: definitions;
  event_aggregates: event_aggregates;
  events: events;
  follows: follows;
  likes: likes;
  migration_history: migration_history;
  notifications: notifications;
  refresh_tokens: refresh_tokens;
  reports: reports;
  terms: terms;
  user_badge_progress: user_badge_progress;
  user_badges: user_badges;
  user_login_streaks: user_login_streaks;
  users: users;
  vw_definitions_with_likes: vw_definitions_with_likes;
  vw_latest_definitions: vw_latest_definitions;
  vw_words_with_stats: vw_words_with_stats;
  words: words;
}

export type DBTableNames = keyof DBTableMap;
