/**
 * This file was automatically generated by scripts/generate-db-types.js.
 * DO NOT EDIT MANUALLY.
 */

export type AdminUsersTable = {
  id: string;
  username: string;
  password: string;
  role: any;
  must_change_password?: boolean | null;
  last_login?: any | null;
  created_at?: any | null;
  updated_at?: any | null;
  deleted_at?: any | null;
};

export type BadgesTable = {
  id: string;
  code: string;
  name: string;
  description?: string | null;
  icon?: string | null;
  category: string;
  event_type: string;
  threshold: number;
  is_active: boolean;
  created_at: any;
  updated_at: any;
};

export type DefinitionHistoriesTable = {
  id: string;
  definition_id: string;
  content: string;
  tags?: any | null;
  media_urls?: any | null;
  created_at: any;
};

export type DefinitionsTable = {
  id: string;
  content: string;
  word_id: string;
  user_id: string;
  created_at: any;
  updated_at: any;
  deleted_at?: any | null;
  tags?: any | null;
  media_urls?: any | null;
  is_public: boolean;
};

export type EventAggregatesTable = {
  id: string;
  type: string;
  user_id?: string | null;
  aggregate_key: string;
  count: number;
  first_occurrence: any;
  last_occurrence: any;
  metadata?: any | null;
  period_start: any;
  period_end: any;
  created_at: any;
  updated_at: any;
};

export type EventsTable = {
  id: string;
  type: string;
  user_id?: string | null;
  payload: any;
  metadata?: any | null;
  created_at: any;
};

export type FollowsTable = {
  id: string;
  follower_id: string;
  following_id: string;
  created_at: any;
  updated_at: any;
  deleted_at?: any | null;
};

export type LikesTable = {
  id: string;
  user_id: string;
  definition_id: string;
  created_at: any;
  updated_at: any;
  deleted_at?: any | null;
};

export type MigrationHistoryTable = {
  sequence_id: number;
  filename: string;
  executed_at?: any | null;
};

export type NotificationsTable = {
  id: string;
  user_id: string;
  type: string;
  title: string;
  message?: string | null;
  actor_id?: string | null;
  target_url?: string | null;
  is_read: boolean;
  created_at: any;
  updated_at: any;
  deleted_at?: any | null;
};

export type ReportsTable = {
  id: string;
  reporter_id: string;
  reported_user_id: string;
  definition_id?: string | null;
  reason: string;
  status: string;
  description?: string | null;
  created_at: any;
  updated_at: any;
  resolved_at?: any | null;
};

export type UserBadgeProgressTable = {
  id: string;
  user_id: string;
  event_type: string;
  count: number;
  last_updated: any;
  created_at: any;
};

export type UserBadgesTable = {
  id: string;
  user_id: string;
  badge_id: string;
  earned_at: any;
};

export type UsersTable = {
  id: string;
  google_id?: string | null;
  email: string;
  nickname: string;
  profile_picture?: string | null;
  created_at: any;
  updated_at: any;
  deleted_at?: any | null;
  bio?: string | null;
  suspended_at?: any | null;
};

export type VwDefinitionsWithLikesTable = {
  id?: string | null;
  content?: string | null;
  word_id?: string | null;
  user_id?: string | null;
  created_at?: any | null;
  updated_at?: any | null;
  deleted_at?: any | null;
  tags?: any | null;
  media_urls?: any | null;
  is_public?: boolean | null;
  likes_count?: string | null;
};

export type VwLatestDefinitionsTable = {
  id?: string | null;
  content?: string | null;
  word_id?: string | null;
  user_id?: string | null;
  created_at?: any | null;
  updated_at?: any | null;
  deleted_at?: any | null;
  tags?: any | null;
  media_urls?: any | null;
  is_public?: boolean | null;
  user_nickname?: string | null;
  user_profile_picture?: string | null;
  likes_count?: string | null;
};

export type VwWordsWithStatsTable = {
  id?: string | null;
  term?: string | null;
  user_id?: string | null;
  created_at?: any | null;
  updated_at?: any | null;
  deleted_at?: any | null;
  definition_count?: string | null;
  public_definition_count?: string | null;
  contributor_count?: string | null;
};

export type WordsTable = {
  id: string;
  term: string;
  user_id: string;
  created_at: any;
  updated_at: any;
  deleted_at?: any | null;
};

export type DBTableNames = 
  | "admin_users"
  | "badges"
  | "definition_histories"
  | "definitions"
  | "event_aggregates"
  | "events"
  | "follows"
  | "likes"
  | "migration_history"
  | "notifications"
  | "reports"
  | "user_badge_progress"
  | "user_badges"
  | "users"
  | "vw_definitions_with_likes"
  | "vw_latest_definitions"
  | "vw_words_with_stats"
  | "words";
