/**
 * This file was automatically generated by scripts/generate-db-types.js.
 * DO NOT EDIT MANUALLY.
 */

export type AdminRole = 
  | "super_admin"
  | "developer"
  | "operator";

export type AdminUsers = {
  id: string;
  username: string;
  password: string;
  role: AdminRole;
  mustChangePassword?: boolean | null;
  lastLogin?: Date | null;
  createdAt?: Date | null;
  updatedAt?: Date | null;
  deletedAt?: Date | null;
};

export type Badges = {
  id: string;
  code: string;
  name: string;
  description?: string | null;
  icon?: string | null;
  category: string;
  eventType: string;
  threshold: number;
  isActive: boolean;
  createdAt: Date;
  updatedAt: Date;
  deletedAt?: Date | null;
};

export type DefinitionHistories = {
  id: string;
  definitionId: string;
  content: string;
  tags?: any | null;
  mediaUrls?: any | null;
  createdAt: Date;
};

export type Definitions = {
  id: string;
  content: string;
  wordId: string;
  userId: string;
  termId: string;
  createdAt: Date;
  updatedAt: Date;
  deletedAt?: Date | null;
  tags?: any | null;
  mediaUrls?: any | null;
  isPublic: boolean;
};

export type EventAggregates = {
  id: string;
  type: string;
  userId?: string | null;
  aggregateKey: string;
  count: number;
  firstOccurrence: Date;
  lastOccurrence: Date;
  metadata?: any | null;
  periodStart: Date;
  periodEnd: Date;
  createdAt: Date;
  updatedAt: Date;
  deletedAt?: Date | null;
};

export type Events = {
  id: string;
  type: string;
  userId?: string | null;
  payload: any;
  metadata?: any | null;
  createdAt: Date;
  updatedAt: Date;
  deletedAt?: Date | null;
};

export type Follows = {
  id: string;
  followerId: string;
  followingId: string;
  createdAt: Date;
  updatedAt: Date;
  deletedAt?: Date | null;
};

export type Likes = {
  id: string;
  userId: string;
  definitionId: string;
  createdAt: Date;
  updatedAt: Date;
  deletedAt?: Date | null;
};

export type MigrationHistory = {
  sequenceId: number;
  filename: string;
  executedAt?: Date | null;
};

export type Notifications = {
  id: string;
  userId: string;
  type: string;
  title: string;
  message?: string | null;
  actorId?: string | null;
  targetUrl?: string | null;
  isRead: boolean;
  createdAt: Date;
  updatedAt: Date;
  deletedAt?: Date | null;
};

export type RefreshTokens = {
  id: string;
  userId: string;
  token: string;
  expiresAt: Date;
  createdAt: Date;
  updatedAt: Date;
  deletedAt?: Date | null;
  fromAdmin: boolean;
};

export type Reports = {
  id: string;
  reporterId: string;
  reportedUserId: string;
  definitionId?: string | null;
  reason: string;
  status: string;
  description?: string | null;
  createdAt: Date;
  updatedAt: Date;
  resolvedAt?: Date | null;
};

export type Terms = {
  id: string;
  text: string;
  number: number;
  createdAt: Date;
  updatedAt: Date;
  deletedAt?: Date | null;
};

export type UserBadgeProgress = {
  id: string;
  userId: string;
  eventType: string;
  count: number;
  lastUpdated: Date;
  createdAt: Date;
  updatedAt: Date;
  deletedAt?: Date | null;
};

export type UserBadges = {
  id: string;
  userId: string;
  badgeId: string;
  earnedAt: Date;
  updatedAt: Date;
  deletedAt?: Date | null;
};

export type UserLoginStreaks = {
  id: string;
  userId: string;
  currentStreak: number;
  longestStreak: number;
  lastLoginAt: Date;
  createdAt?: Date | null;
  updatedAt?: Date | null;
  deletedAt?: Date | null;
};

export type Users = {
  id: string;
  googleId?: string | null;
  email: string;
  nickname: string;
  profilePicture?: string | null;
  createdAt: Date;
  updatedAt: Date;
  deletedAt?: Date | null;
  bio?: string | null;
  suspendedAt?: Date | null;
};

export type VwDefinitionsWithLikes = {
  id?: string | null;
  content?: string | null;
  wordId?: string | null;
  userId?: string | null;
  termId?: string | null;
  createdAt?: Date | null;
  updatedAt?: Date | null;
  deletedAt?: Date | null;
  tags?: any | null;
  mediaUrls?: any | null;
  isPublic?: boolean | null;
  likesCount?: string | null;
};

export type VwLatestDefinitions = {
  id?: string | null;
  content?: string | null;
  wordId?: string | null;
  userId?: string | null;
  termId?: string | null;
  createdAt?: Date | null;
  updatedAt?: Date | null;
  deletedAt?: Date | null;
  tags?: any | null;
  mediaUrls?: any | null;
  isPublic?: boolean | null;
  userNickname?: string | null;
  userProfilePicture?: string | null;
  likesCount?: string | null;
};

export type VwWordsWithStats = {
  id?: string | null;
  term?: string | null;
  userId?: string | null;
  createdAt?: Date | null;
  updatedAt?: Date | null;
  deletedAt?: Date | null;
  definitionCount?: string | null;
  publicDefinitionCount?: string | null;
  contributorCount?: string | null;
};

export type Words = {
  id: string;
  term: string;
  userId: string;
  createdAt: Date;
  updatedAt: Date;
  deletedAt?: Date | null;
};

